name: plantoid
description: Helping you keep track of your plants, and when to water them.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+10

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.14.11

  intl: ^0.15.7

  firebase_core: ^0.4.0+1
  cloud_firestore: ^0.12.1
  firebase_storage: ^3.0.0
  firebase_auth: ^0.11.1+3
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.1
  firebase_messaging: ^5.0.1+1

  camera: ^0.5.2+1
  native_device_orientation: ^0.2.0
  path_provider: ^0.5.0+1
  cached_network_image: ^0.8.0
  mime: ^0.9.6+2

  timeago: ^1.3.0

  flutter_stream_friends: ^0.8.0
  sealed_unions: ^3.0.1
  tuple: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^4.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/watering_can.webp
   - assets/icons/yellow_flower.webp
   - assets/icons/google.webp
   - assets/icons/facebook.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
  - family: Google Sans
    fonts:
    - asset: fonts/GoogleSans-Regular.ttf
    - asset: fonts/GoogleSans-Medium.ttf
      weight: 500
    - asset: fonts/GoogleSans-Bold.ttf
      weight: 700

  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
